// front/src/app/components/layout.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: `
    <div class="flex h-screen bg-gray-950 text-gray-100">
      <!-- Sidebar -->
      <aside class="w-60 border-r border-gray-800 flex flex-col">
        <div class="p-5 border-b border-gray-800">
          <div class="flex items-center gap-2">
            <span class="text-lg font-bold tracking-tight">EssLearn</span>
          </div>
        </div>
        <nav class="flex-1 p-3 space-y-1">
          <a routerLink="/" routerLinkActive="active" class="nav-link">Dashboard</a>
          <a routerLink="/fields" routerLinkActive="active" class="nav-link">Fields</a>
          <a routerLink="/import" routerLinkActive="active" class="nav-link">Import</a>
        </nav>
      </aside>
      <main class="flex-1 p-8 overflow-y-auto">
        <router-outlet></router-outlet>
      </main>
    </div>
  `,
  styles: [`
    .nav-link {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 0.625rem 0.75rem;
      border-radius: 0.5rem;
      font-size: 0.875rem;
      font-weight: 500;
      color: #a1a1aa;
      transition: color 0.2s, background 0.2s;
      text-decoration: none;
    }
    .nav-link.active {
      background: rgba(99, 102, 241, 0.15);
      color: #818cf8;
    }
    .nav-link:hover {
      color: #e5e7eb;
      background: rgba(31, 41, 55, 0.5);
    }
  `],
})
export class LayoutComponent {}

// frontend/src/components/Layout.tsx
import { NavLink, Outlet } from 'react-router-dom';
import { LayoutDashboard, FolderOpen, Import, Play } from 'lucide-react';

const navItems = [
  { to: '/', icon: LayoutDashboard, label: 'Dashboard' },
  { to: '/fields', icon: FolderOpen, label: 'Fields' },
  { to: '/import', icon: Import, label: 'Import' },
];

export default function Layout() {
  return (
    <div className="flex h-screen bg-gray-950 text-gray-100">
      {/* Sidebar */}
      <aside className="w-60 border-r border-gray-800 flex flex-col">
        <div className="p-5 border-b border-gray-800">
          <div className="flex items-center gap-2">
            <Play className="w-6 h-6 text-indigo-400" />
            <span className="text-lg font-bold tracking-tight">EssLearn</span>
          </div>
        </div>
        <nav className="flex-1 p-3 space-y-1">
          {navItems.map(({ to, icon: Icon, label }) => (
            <NavLink
              key={to}
              to={to}
              end={to === '/'}
              className={({ isActive }) =>
                `flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors ${
                  isActive
                    ? 'bg-indigo-500/15 text-indigo-400'
                    : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
                }`
              }
            >
              <Icon className="w-4.5 h-4.5" />
              {label}
            </NavLink>
          ))}
        </nav>
      </aside>

      {/* Main content */}
      <main className="flex-1 overflow-y-auto">
        <div className="max-w-7xl mx-auto p-6">
          <Outlet />
        </div>
      </main>
    </div>
  );
}
